# Controls when the workflow will run
on:
   pull_request:
    types:
      - closed
name: Release Sample Files

jobs:
  build:
    name: Create Release
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build Module
        shell: pwsh
        run: ./Samples/ZipForRelease.ps1
      - name: Create a Release
        uses: elgohr/Github-Release-Action@v5
        env:
          GH_TOKEN: ${{ secrets.DYNAMO_ACTIONS_TOKEN  }}
        with:
          title: Generative Design Primer Sample Files
          workdir: "./Release/*.zip"   
